DEBUG 2020-05-09 23:11:20.014 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-09 23:11:20.030 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-09 23:11:20.030 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-09 23:11:20.031 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
DEBUG 2020-05-09 23:11:20.039 UTC: 	 Checking credentials
DEBUG 2020-05-09 23:11:20.039 UTC: 	 Found proxy file /tmp/x509up_u5729
DEBUG 2020-05-09 23:11:20.039 UTC: 	 Getting proxy life time left
DEBUG 2020-05-09 23:11:20.142 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u5729 -timeleft
 output : 43053

 error: 
 retcode : 0
DEBUG 2020-05-09 23:11:20.246 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u5729 -actimeleft
 output : 43053

 error: 
 retcode : 0
DEBUG 2020-05-09 23:11:20.246 UTC: 	 Proxy valid for 11:57:33 hours
ERROR 2020-05-09 23:11:20.247 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2020-05-09 23:11:20.247 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
DEBUG 2020-05-12 18:22:41.718 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-12 18:22:41.736 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-12 18:22:41.736 UTC: 	 Executing command: 'status'
DEBUG 2020-05-12 18:22:41.737 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2020-05-12 18:22:41.761 UTC: 	 Error: crab_MVA_Q is not a valid CRAB project directory.
ERROR 2020-05-12 18:22:41.761 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_MVA_Q is not a valid CRAB project directory.
